### ISSUE TITLE
Support for building RPM packages

### ISSUE THREAD

**Issue by cottsay** [ros-infrastructure/ros_buildfarm#736]
Major Features:
- [x] Release Status Page: #713, #727
- [x] Repository Status Page: #781
- [x] Trigger Jobs: #712, #713, #715
- [x] Package Import: #721
- [x] Sync to Testing: #732 
- [x] Source Package: #733 
- [x] Binary Package: #735 
- [x] Sync to Main: #771
- [x] Repository Import: #779

Minor Features:
- [x] Symbol packages:  #806
- [x] Metadata signing: ros-infrastructure/cookbook-ros-buildfarm#61
- [x] ~~Travis~~ **GitHub Action** testing: #866

Known Limitations:
- No retry on repository metadata download failures
  - This is the biggest source of sporadic failures in the jobs right now. We're updating the building repository very often, and sometimes a builder downloads the `repomd.xml` right before we update it, and then tries to download the wrong `repomd.xml.asc` or `primary.xml.gz`. I'm not aware of any way to trick dnf into re-downloading the `repomd.xml` when this happens. One mitigation we've discussed is caching the `primary.xml.gz` files in nginx, but that doesn't solve the GPG signature failure regarding `repomd.xml.asc`.
- ~~"Dry Run" options don't all work~~
- ~~May need to limit parallelization (`-j1`)~~ #755 
- No caching for packages or buildroot at all
  - Everything is happening in containers, and I'm not sure of the best way to implement shared and concurrent cache access in mock. We could probably shave at least a minute off from each job if we were able to implement this.
- Maintainer E-mails aren't printed when the build fails
  - Maybe grabbing the maintainer E-mails from the distro cache would be a better solution than extracting them from the RPM.
- Some scripts require deb resources from bootstrap repos, so you can't create a true "RPM-only" instance
  - I discovered this a while ago, but IIRC, the sync-to-testing threshold calculation was the issue. We should re-visit this.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/rpm-packaging-support-in-ros-buildfarm/15672/1

**Comment by cottsay** [comment]
There are still small tasks related to RPM support that we will still need to tackle someday, but we've reached parity for all of the major buildfarm features between debian and RPM builds. I think it's time to close this tracking issue.
